### ISSUE TITLE
Update wiringPi by installer script

### ISSUE THREAD

**Issue by sohamakl** [LukeSkywalker92/TeleFrame#110]
Could someone add the update of wiringPi to the installer script, please.

The new version supports hadware up to Raspberry Pi 4B.

```
cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb
```

**Comment by gegu** [comment]
Since wiringPi is not required for normal operation of TeleFrame, I do not want to do this in the installer, Because this will leave the normal installation path, even if it is currently required.

I have added a notice and installation instructions in the README for installing the Addon newImageLED.
