### ISSUE TITLE
JavaScript SyntaxError - imageWatchdog.js

### ISSUE THREAD

**Issue by Baule8520** [LukeSkywalker92/TeleFrame#143]
Hello,

from one day to another I am getting attached error.

Update und Reinstall didn`t fix the problem.

Do you have an idea?

![Javascript Error](https://user-images.githubusercontent.com/58749158/97310632-b7d5c080-1863-11eb-977e-d91b3c9f5f39.jpg)

Thank you!

**Comment by LukeSkywalker92** [comment]
Hey,

it looks like your `images.json` file is damaged.
To check if this is the case you could rename your `images.json` into `images.json.bak` and see if the problem is fixed.
If yes, you need to find what is wrong with your `images.json` file. To do that you can copy the content to a json linter...If you found the problem you can repair the `images.json.bak` and rename it again to `images.json`.

**Comment by Baule8520** [comment]
Thank you!
